name: vsmpOrigins
version: '1.1'
main: org.shingas.vsmpOrigins.vsmpOrigins
api-version: '1.21'
authors: [Shingas]
description: Shingas Custom Origin Addon
depend: [Origins-Reborn]
commands:
  vamptoggle:
    description: "Toggles on/off the vampire transformation when killing players."
    usage: "/vamptoggle <on/off>"
  dwarfvision:
    description: "Toggles on/off the dwarf's night vision."
    usage: "/dwarfvision <on/off>"